name: Publish to NuGet

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.x"
          
      - name: Test
        run: dotnet test
  
  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.x"
          
      - name: Build
        run: dotnet build --configuration Release --output Build
        
      - name: Store build
        uses: actions/upload-artifact@v2
        with:
          name: checkout
          path: ${{ github.workspace }}
  upload:
    name: Upload
    runs-on: ubuntu-latest
    needs: 
      - build
    steps:
      - name: Restore build
        uses: actions/download-artifact@v2
        with:
          name: build
          
      - name: Pack
        run: dotnet pack --output Build
        
      - name: Upload to NuGet
        env: 
          API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./Build/*.nupkg --api-key $API_KEY


on:
  release:
    types:
      - published
  push:
    branches:
      - master